[window]
padding = { x = 10, y = 10 }
opacity = 0.95
decorations = "none"

[font]
size = 11.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

# Ported from notusknot/dotfiles-nix (see README credits)
[colors.primary]
background = "#292a37"
foreground = "#d9e0ee"

[colors.cursor]
text = "#292a37"
cursor = "#efb993"

[colors.normal]
black = "#303241"
red = "#ec6a88"
green = "#3fdaa4"
yellow = "#efb993"
blue = "#3fc6de"
magenta = "#b771dc"
cyan = "#6be6e6"
white = "#d9e0ee"

[colors.bright]
black = "#393a4d"
red = "#e95678"
green = "#29d398"
yellow = "#efb993"
blue = "#26bbd9"
magenta = "#b072d1"
cyan = "#59e3e3"
white = "#d9e0ee"

[shell]
program = "/usr/bin/zsh"
