background {
    monitor =
    color = rgba(292a37ee)
    blur_passes = 2
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    outer_color = rgba(b072d1ee)
    inner_color = rgba(44465cee)
    font_color = rgba(d9e0eeee)
    fade_on_empty = true
    placeholder_text = <span foreground="##d9e0ee">Password...</span>
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M:%S")"
    color = rgba(d9e0eeee)
    font_size = 64
    position = 0, 150
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = rgba(9699b7ee)
    font_size = 18
    position = 0, 60
    halign = center
    valign = center
}
