#!/usr/bin/env bash
set -euo pipefail
#-------------------------------------------------------------------------
# Lays out a 3-monitor Hyprland setup:
#   - a vertical (portrait) monitor on the left
#   - the main monitor along the bottom, normal orientation
#   - a monitor above the main one, rotated 180 (upside down)
#
# Reads currently connected monitors from `hyprctl monitors`, lets you pick
# which physical monitor is which role, applies the layout live via
# `hyprctl keyword monitor`, and saves it to ~/.config/hypr/monitors.conf
# so it survives a restart (source it from hyprland.conf -- see the note
# printed at the end).
#-------------------------------------------------------------------------

if ! command -v hyprctl >/dev/null 2>&1; then
    echo "ERROR: hyprctl not found -- run this from inside a Hyprland session." >&2
    exit 1
fi

names=()
widths=()
heights=()
rates=()

idx=-1
while IFS= read -r line; do
    if [[ "${line}" =~ ^Monitor\ ([^[:space:]]+)\ \(ID\ [0-9]+\): ]]; then
        names+=("${BASH_REMATCH[1]}")
        idx=$((idx + 1))
    elif [[ "${line}" =~ ^[[:space:]]*([0-9]+)x([0-9]+)@([0-9.]+)\ at\ (-?[0-9]+)x(-?[0-9]+) ]] && [[ ${idx} -ge 0 ]]; then
        widths[${idx}]="${BASH_REMATCH[1]}"
        heights[${idx}]="${BASH_REMATCH[2]}"
        rates[${idx}]="${BASH_REMATCH[3]}"
    fi
done < <(hyprctl monitors)

if [[ ${#names[@]} -lt 3 ]]; then
    echo "ERROR: only found ${#names[@]} monitor(s) via hyprctl -- need 3." >&2
    exit 1
fi

echo "Detected monitors:"
for i in "${!names[@]}"; do
    printf "  [%d] %-10s %sx%s@%s\n" "${i}" "${names[${i}]}" "${widths[${i}]}" "${heights[${i}]}" "${rates[${i}]}"
done
echo

read -rp "Which number is the VERTICAL monitor (left side)? " V_IDX
read -rp "Which number is the MAIN monitor (bottom)? " B_IDX
read -rp "Which number is the UPSIDE-DOWN monitor (top)? " T_IDX

for n in "${V_IDX}" "${B_IDX}" "${T_IDX}"; do
    if ! [[ "${n}" =~ ^[0-9]+$ ]] || [[ "${n}" -ge ${#names[@]} ]]; then
        echo "ERROR: '${n}' is not a valid monitor number." >&2
        exit 1
    fi
done
if [[ "${V_IDX}" == "${B_IDX}" || "${V_IDX}" == "${T_IDX}" || "${B_IDX}" == "${T_IDX}" ]]; then
    echo "ERROR: pick three different monitors." >&2
    exit 1
fi

echo
echo "Which way is the vertical monitor physically rotated?"
echo "  1) 90 clockwise   (top of the panel now faces right)  [default]"
echo "  2) 90 counter-clockwise / 270 (top of the panel now faces left)"
read -rp "Choice [1/2]: " ROT_CHOICE
VERT_TRANSFORM=1
[[ "${ROT_CHOICE:-1}" == "2" ]] && VERT_TRANSFORM=3

V_NAME="${names[${V_IDX}]}"; V_W="${widths[${V_IDX}]}"; V_H="${heights[${V_IDX}]}"; V_RATE="${rates[${V_IDX}]}"
B_NAME="${names[${B_IDX}]}"; B_W="${widths[${B_IDX}]}"; B_H="${heights[${B_IDX}]}"; B_RATE="${rates[${B_IDX}]}"
T_NAME="${names[${T_IDX}]}"; T_W="${widths[${T_IDX}]}"; T_H="${heights[${T_IDX}]}"; T_RATE="${rates[${T_IDX}]}"

# A 90/270 transform swaps the on-screen width/height; 180 (upside down)
# and 0 (normal) don't.
V_EFF_W=${V_H}

TOP_X=${V_EFF_W}
TOP_Y=0
BOTTOM_X=${V_EFF_W}
BOTTOM_Y=${T_H}

VERT_LINE="${V_NAME},${V_W}x${V_H}@${V_RATE},0x0,1,transform,${VERT_TRANSFORM}"
TOP_LINE="${T_NAME},${T_W}x${T_H}@${T_RATE},${TOP_X}x${TOP_Y},1,transform,2"
BOTTOM_LINE="${B_NAME},${B_W}x${B_H}@${B_RATE},${BOTTOM_X}x${BOTTOM_Y},1"

apply_monitor() {
    local line="$1" out
    echo "  monitor = ${line}"
    if ! out="$(hyprctl keyword monitor "${line}" 2>&1)"; then
        echo "    ERROR from hyprctl: ${out}" >&2
    elif [[ -n "${out}" && "${out}" != "ok" ]]; then
        echo "    hyprctl response: ${out}"
    fi
}

echo
echo "Applying:"
apply_monitor "${VERT_LINE}"
apply_monitor "${TOP_LINE}"
apply_monitor "${BOTTOM_LINE}"

CONF="${HOME}/.config/hypr/monitors.conf"
mkdir -p "$(dirname "${CONF}")"
{
    echo "# Generated by hypr-monitor-layout.sh"
    echo "# ${V_NAME}: vertical, left | ${B_NAME}: main, bottom | ${T_NAME}: upside-down, top"
    echo "monitor = ${VERT_LINE}"
    echo "monitor = ${TOP_LINE}"
    echo "monitor = ${BOTTOM_LINE}"
} > "${CONF}"

echo "Saved to ${CONF}"
echo
echo "To make this stick across restarts, add this to ~/.config/hypr/hyprland.conf"
echo "(and remove/comment out any other 'monitor =' line, e.g. the"
echo "'monitor = , preferred, auto, auto' one, so they don't conflict):"
echo
echo "  source = ~/.config/hypr/monitors.conf"
echo
echo "NOTE: if you re-run this script later, do it right after 'hyprctl reload'"
echo "or a fresh Hyprland start -- once a transform is applied, hyprctl monitors"
echo "reports the already-rotated resolution, which would throw off the numbers"
echo "here on a second pass."
